name: xmpp-bridge-openfire

services:
  openfire:
    image: nasqueron/openfire:4.7.1
    container_name: openfire-dev
    restart: unless-stopped
    ports:
      - "9090:9090" # Admin console (HTTP)
      - "9091:9091" # Admin console (HTTPS)
      - "5222:5222" # XMPP client connections
      - "5223:5223" # XMPP client connections (SSL)
      - "5269:5269" # XMPP server connections
      - "7777:7777" # File transfer proxy
    volumes:
      - openfire_data:/var/lib/openfire

volumes:
  openfire_data:
    driver: local
